### ISSUE TITLE
For Cycle 18

### ISSUE THREAD

**Issue by oscarguindzberg** [bisq-network/compensation#687] opened 2020-10-21 18:33 UTC
## Summary

> _Specify the total amount of BSQ you are requesting, along with the USD total and BSQ/USD rate (don't include the brackets!):_

- **BSQ requested**: **`14705.88`** 
- USD requested: 10000 
- BSQ rate: 0.68 USD per BSQ 
- Previous compensation request (if applicable): #662  

## Contributions delivered

> _Add contributions you have [delivered](https://github.com/bisq-network/proposals/issues/19) and roles you have performed here as new rows in the table below. Role line-items should include an asterisk (*) in the team column._

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Segwit for bisq btc wallet | dev | 10000 | https://github.com/bisq-network/bisq/pull/4568 | |

Context: 
https://github.com/bisq-network/projects/issues/42
https://github.com/bisq-network/proposals/issues/247

## Contributions in progress

> _Provide links to work you're involved with that is still [in progress](https://github.com/bisq-network/proposals/issues/19). **This section is optional (the linter ignores it),** and is for your own benefit in keeping track of what you're doing and keeping other contributors up to date with the same._

**Comment by oscarguindzberg** [comment] 2020-10-23 21:08
This compensation proposal is subject to the terms of DAO proposal 247 https://github.com/bisq-network/proposals/issues/247 and will be paid from the special BTC multisig escrow to @oscarguindzberg as follows, pending DAO approval in Cycle 18 voting:

USD: 10000
BSQ: 10000 / .68 = 14705.88 BSQ
BTC: 14705.88 * 0.00006239 = 0.9175, minus 0.01470588 BTC for comp req = 0.90279412 BTC net to oscar
Note: Using 30 days average 6239 sats BSQ/BTC rate from screenshot below taken at the time of compensation proposal creation

<img width="1170" alt="bsq-rate" src="https://user-images.githubusercontent.com/1145132/97054189-b43bf400-155a-11eb-9803-a2ff14495016.png">

**Comment by wiz** [comment] 2020-10-24 05:28
@oscarguindzberg regarding the 30 days average price for BSQ/BTC, recently it seems there were some very high priced BSQ trades that moved the average BSQ/BTC rate much higher:

<img width="318" alt="Screen Shot 2020-10-24 at 14 08 33" src="https://user-images.githubusercontent.com/232186/97068715-20733200-1605-11eb-813c-746176ac6a58.png">

considering that these outlier trades are obviously manipulating the price much higher, maybe we should remove the very high priced trades from the calculation for the 30 day weighted average price this cycle. does that sound reasonable to you?

**Comment by wiz** [comment] 2020-10-24 05:41
Alternatively I made another proposal how to calculate the "fair market price" of BSQ: https://github.com/bisq-network/proposals/issues/269

**Comment by chimp1984** [comment] 2020-10-25 21:18
0.90279412 BTC is 11,774 USD according to:
https://www.google.com/search?client=firefox-b-d&ei=4-qVX6ufFqSx5wKhuK6oCg&q=0.90279412+BTC+in+usd&oq=0.90279412+BTC+in+usd

The BSQ rate should cancel itself out from my understanding (not knowing the details of the contract).

**Comment by sqrrm** [comment] 2020-10-25 22:40
The payout to @oscarguindzberg is denominated in USD. The exchange rate should in my opinion be the Bisq average from our price nodes at the time of payout. Another source could be used, but I think that doesn't make sense since we have one that's used as the accepted USD/BTC rate for all other usages within Bisq.

**Comment by chimp1984** [comment] 2020-10-25 23:34
I just looked at the last comp request https://github.com/bisq-network/compensation/issues/662 and the same calculation was done which resulted in about 1500 USD loss due the BSQ volatility. I think we have to fix that the calculation is not adding BSQ volatility and just convert the USD to BTC and replay the loss @oscarguindzberg suffered at last cycle.

**Comment by wiz** [comment] 2020-10-26 01:16
if you want to be the guarantor and deposit 4 BTC in the multisig escrow, we can make a new deal with oscar using whatever terms you want, otherwise right now i am just mediating the terms agreed between the parties that are defined in https://github.com/bisq-network/proposals/issues/247

**Comment by chimp1984** [comment] 2020-10-26 02:50
Ah ok. I have not read the initial proposal before...

So after doing a few more calculations I think the problem is that we have both the USD/BTC volatility as well as the BTC/BSQ volatility as part of the model and we apply the 30 or 90 days average on both BSQ and BTC.

The calculation with 30 days average and excluded outliers (1% threshold - see https://github.com/bisq-network/bisq/pull/4706) would be:
BTC: 14705,88 * 0,00005652 = 0,8311763376 BTC
0,8311763376 BTC is 10861 USD @13068 BTC/USD
A average rate BTC/USD rate of 12031 would result in 10 000 USD. I have not run a calculation to check what was the 30/90 days average Btc price (from Bisq trades, which might be a bit different than global market rate), but it feels realistic as prices have just recently spiked to 13k.

<img width="1194" alt="1perc" src="https://user-images.githubusercontent.com/54558767/97127846-bd6ac380-1708-11eb-807e-499599c7db25.png">

I don't know how to deal best with the situation. The terms of the proposal/contract are matching the way it was calculated. I think the uncertainties of volatility on BTC and BSQ have been under-estimated but are a fact which we have to deal with. 
The chosen model distributes the volatility risk between the guarantor and @oscarguindzberg . If we would change it to convert the requested USD directly to BTC it would be only on the shoulders of the guarantor. 
Simple though example: Imagine BTC goes down to 3000 USD. The guarantor would lose then more than 3 BTC for a single months payment (and Bisq would likely not get segwit completed). On the other side if BTC goes up to 30 K @oscarguindzberg would only get 0.33 BTC and if BTC settles back down to 10k afterwards his monthly payment was much lower as expected. Of course we cannot avoid volatility but with the current model we smoothen out the risk over a period of time. It makes it harder to understand intuitively but I think its more fair and safe.

@oscarguindzberg What do you think? If you agree can you adjust your calculation with the adjusted rate where we filtered out the outliers which are suspect to price manipulation?

**Comment by oscarguindzberg** [comment] 2020-10-26 14:28
I agree to use the BSQ/BTC rate suggested by @chimp1984.

This is the updated calculation:

USD: 10000
BSQ: 10000 / .68 = 14705.88 BSQ
BTC: 14705.88 * 0.00005652 = 0,83117633, minus 0,01470588 BTC for comp req = 0,81647045 BTC net to oscar

**Comment by ripcurlx** [comment] 2020-10-27 18:53
As stand in [team lead](https://bisq.wiki/Compensation#Team_Lead) I approve this request.

**Comment by ripcurlx** [comment] 2020-11-02 08:53
@oscarguindzberg Can you please post your TXID for this CR? Thanks!

**Comment by oscarguindzberg** [comment] 2020-11-02 13:31
0e589f7d3894c40c50eb32b00ed5c8789b6122ad2dded0e3042456b3216af0c1

**Comment by MwithM** [comment] 2020-11-08 15:57
Closed as accepted.

**Closed as completed by MwithM** 2020-11-08 15:57 UTC
Labels: was:accepted, team:dev, parsed:valid
