### ISSUE TITLE
For Cycle 9

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/compensation#435] opened 2019-12-13 01:41 UTC
## Summary
 - BSQ requested: 3880 BSQ (2600 USD with conversion rate 0.67 USD/BSQ)

EDIT: As @beingindot observed the real number would be 3100 USD not 2600 USD. It is too late now to fix as the proposal phase is over. I will add the 500 USD to the next cycle with the conversion rate of that cycle.
 
### Development work:

[Add short cut list](https://github.com/bisq-network/bisq/pull/3695)
Requested: 300 USD

[Add report feature for disputes](https://github.com/bisq-network/bisq/pull/3790)
Requested: 200 USD

### Staged for review:

[Improve handling of spv resync edge case](https://github.com/bisq-network/bisq/pull/3821)
Requested: 600 USD

[Add 2 new columns to vote result](https://github.com/bisq-network/bisq/pull/3822)
Requested: 400 USD

[Make all DAO screen tables resize to max. screen height](https://github.com/bisq-network/bisq/pull/3823)
Requested: 100 USD

[Increase security deposits](https://github.com/bisq-network/bisq/pull/3826)
Requested: 300 USD

[Use min. refund at mediated payout](https://github.com/bisq-network/bisq/pull/3827)
Requested: 200 USD

[Only move to failed trades if the reject msg is critical ](https://github.com/bisq-network/bisq/pull/3830)
Requested: 100 USD

### User support:
Helped 9 users to solve problems with locked up funds.
Requested: 900 USD

#### Details:
Here is a summary of the cases I have handled:

Most cases have been rather trivial (invalid tx, update problem, unstable internet) and 1 case which required expert skills. With our intended support system all the cases expect the one of @ipharmaticist sould be handled by support agents without need of a dev. The reasons for @ipharmaticist problem is fixed by 1.2.4.  

@objectorange:
Reason: Bad internet, after repeated DAO resynced he got BSQ confirmed. Case closed.

@zanetti74:
Reason: Invalid tx case. Trader still don't undestand it mentally but case is clear to me and no funds locked/lost. Case closed as I did my best to explain but cannot repeat endlessly.

@llohop
Reason: Invalid tx case. Case closed.

@wwy55:
Reason: Updated to 1.2. while having trade with old version. Waiting for old arbitrator to make manual payout.  

@boogeze:
Reason: Update to 1.2. while having trade with old version. Waiting for old arbitrator to make manual payout. 

@inpharmaticist:
Reason: Was moved to failed trade with pre 1.2.4 version which had a bug with that handling. Manually (by myself) moved back to open trades. Waiting for refund agent for payout.

@brittkelly
Reason: Invalid tx case. Case closed.

@bigsy_short
Reason: Had error because disk was full. Not resolved as trader did not want to share data.

@dymobisq
Reason: Invalid tx because of 0 BTC output

**Comment by zanetti74** [comment] 2019-12-21 23:50
No you did not help me!

You explained technical terms for a normal Bisq user.

I still do not know how to reach my 0.054 BTC!


Em sáb, 21 de dez de 2019 15:12, chimp1984 <notifications@github.com<mailto:notifications@github.com>> escreveu:
Summary

  *   BSQ requested: TDB

Contributions delivered
Development work:

Add short cut list<https://github.com/bisq-network/bisq/pull/3695>
Requested: 300 USD

Add report feature for disputes<https://github.com/bisq-network/bisq/pull/3790>
Requested: 200 USD

Staged for review:
User support:

Helped 2 users to solve problems with locked up funds.
Requested: TBD

Details:

Here a preliminary summary of the cases I handled and resolved:

There have been 6 cases which have been rather trivial (invalid tx, update problem, unstable internet) and 1 case which required expert skills. With our intended support system all the cases expect the one of @ipharmaticist sould be handled by support agents without need of a dev. The reasons for @ipharmaticist problem is fixed by 1.2.4.

@objectorange<https://github.com/objectorange>:
Reason: Bad internet, after repeated DAO resynced he got BSQ confirmed. Case closed.

@zanetti74<https://github.com/zanetti74>:
Reason: Invalid tx case. Trader still don't undestand it mentally but case is clear to me and no funds locked/lost. Case closed as I did my best to explain but cannot repeat endlessly.

@llohop
Reason: Invalid tx case. Case closed.

@llohop
Reason: Invalid tx case. Case closed.

@wwy55:
Reason: Updated to 1.2. while having trade with old version. Waiting for old arbitrator to make manual payout.

@boogeze:
Reason: Update to 1.2. while having trade with old version. Waiting for old arbitrator to make manual payout.

@inpharmaticist<https://github.com/inpharmaticist>:
Reason: Was moved to failed trade with pre 1.2.4 version which had a bug with that handling. Manually (by myself) moved back to open trades. Waiting for refund agent for payout.

I have one open pending case waiting for response from trader.

**Comment by chimp1984** [comment] 2019-12-22 00:51
> No you did not help me! You explained technical terms for a normal Bisq user. I still do not know how to reach my 0.054 BTC! 

I am sorry, I repeated many times but I fear I cannot help you more. You need to do a basic accounting with the transaction list to see what went in and what went out. This is nothing I can do for you and nothing technical. Feel free to ask for other contributors or a friend who is more familiar with Bitcoin to help you maybe they can explain you better.

**Comment by beingindot** [comment] 2020-01-13 14:44
Here i think the total should come to `3100 USD`

**Comment by zanetti74** [comment] 2020-01-13 14:58
No!

It should be 0,054 BTC that is the amount that I lost in Bisq app.



Em seg, 13 de jan de 2020 11:44, beingindot <notifications@github.com<mailto:notifications@github.com>> escreveu:

Here i think the total should come to 3100 USD

**Comment by chimp1984** [comment] 2020-01-14 12:12
@beingindot Thanks! I made a mistake when updating the support part in the last minute... I will add a comment and add the difference to the next cycles request as its too late now to remove and adda new proposal.

**Comment by chimp1984** [comment] 2020-01-14 12:14
@zanetti74 What you need is an accountant who helps you to count incoming and outgoind funds from Bisq.

**Comment by MwithM** [comment] 2020-01-21 13:37
Closed as accepted.

**Closed by MwithM** 2020-01-21 13:37 UTC
