### ISSUE TITLE
For Cycle 11

### ISSUE THREAD

**Issue by ripcurlx** [bisq-network/compensation#499] opened 2020-02-17 12:51 UTC
## Summary

 - BSQ requested:`5795` (3825 USD @ 0.66 USD/BSQ)

This is a compensation request for contributions delivered from last cycle until now (Mar 16). I calculated the amount based on the new three months average of `0.66 USD` for `1 BSQ` mentioned in https://github.com/bisq-network/compensation/issues/501.

Proposal transaction ID: `dcc894597fb9fdb589c1ba78a3f7b413084795e216540024a51aed3e3c78b054`

### Reviews

_Reviewed PRs:_

<details>
<summary>View all reviewed PRs (27)</summary>

My PR reviews this month were created by reviewing the results of this GitHub Issues search query:
[is:pr reviewed-by:ripcurlx updated:2020-02-14..2020-03-16 sort:updated-desc](https://github.com/bisq-network/bisq/pulls?page=1&q=is%3Apr+reviewed-by%3Aripcurlx+updated%3A2020-02-14..2020-03-16+sort%3Aupdated-desc&utf8=%E2%9C%93)

- [Add local Bitcoin node configuration detection](https://github.com/bisq-network/bisq/pull/3982) `240 USD`
- [Vote Reveal - Silent Fail](https://github.com/bisq-network/bisq/pull/3758) `70 USD`
- [Speed up BSQ supply view load](https://github.com/bisq-network/bisq/pull/3956) `46 USD`
- [Dump failed delayedtx](https://github.com/bisq-network/bisq/pull/4029) `34 USD`
- [Allow 4 refreshes per trade](https://github.com/bisq-network/bisq/pull/3980) `28 USD`
- [Remove unused i18n strings](https://github.com/bisq-network/bisq/pull/3932) `24 USD`
- [Speed up DAO state monitor view load](https://github.com/bisq-network/bisq/pull/4035) `24 USD`
- [Update offer address to new hidden service files](https://github.com/bisq-network/bisq/pull/4021) `22 USD`
- [Added graceful shutdown hook](https://github.com/bisq-network/bisq/pull/4047)

Following PRs Review efforts are so small to track them separately:

- https://github.com/bisq-network/bisq/pull/3968
- https://github.com/bisq-network/bisq/pull/3950
- https://github.com/bisq-network/bisq/pull/3951
- https://github.com/bisq-network/bisq/pull/3958
- https://github.com/bisq-network/bisq/pull/3967
- https://github.com/bisq-network/bisq/pull/3937
- https://github.com/bisq-network/bisq/pull/4002
- https://github.com/bisq-network/bisq/pull/3985
- https://github.com/bisq-network/bisq/pull/3973
- https://github.com/bisq-network/bisq/pull/4008
- https://github.com/bisq-network/bisq/pull/3997
- https://github.com/bisq-network/bisq/pull/3785
- https://github.com/bisq-network/bisq/pull/4010
- https://github.com/bisq-network/bisq/pull/4040
- https://github.com/bisq-network/bisq/pull/4044
- https://github.com/bisq-network/bisq/pull/4048
- https://github.com/bisq-network/bisq/pull/4062
- https://github.com/bisq-network/bisq/pull/4066

**Total USD amount for this remaining PRs**: `400`

</details>

**USD amount requested:** `888`

### Development

I was working mainly on the v1.2.8 release and following PRs were merged to master.
<details>
<summary>View all merged PRs</summary>

My merged PRs this month were created by reviewing the results of this GitHub Issues search query:
[is:pr author:ripcurlx is:merged merged:2020-02-14..2020-03-16 sort:updated-desc](https://github.com/bisq-network/bisq/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aripcurlx+is%3Amerged+merged%3A2020-02-14..2020-03-16+sort%3Aupdated-desc+)

- [Remove redundant closing of connection](https://github.com/bisq-network/bisq/pull/4056) `180 USD`
- [Introduce CoinMarketCap stub to prevent error in existing clients](https://github.com/bisq-network/bisq/pull/4037) `60 USD`
- [Add an empty dummy exchange rate to prevent warning logs](https://github.com/bisq-network/bisq/pull/4043) `50 USD`
- [Accept empty config values](https://github.com/bisq-network/bisq/pull/3978) `50 USD`

Following PRs are minor or not within our priorities:
</details>

**USD amount requested:** `340`

Following PRs are covered by other role efforts already, are minor or  not a prioritiy:
- [Add ARS as supported currency for MoneyGram](https://github.com/bisq-network/bisq/pull/4007) `0 USD`
- [Handle SNAPSHOT versioning differently for rpm packages](https://github.com/bisq-network/bisq/pull/4009) `0 USD`
- [Revert "Vote Reveal - Silent Fail"](https://github.com/bisq-network/bisq/pull/4017) `0 USD`

### Testing
Test reporting for v1.2.8  release testing can be found here: https://bisq.ontestpad.com/project/1/folder/f56/report/?auth=28145f4fcbb5bc8d90372112bb3f00a9

Besides that I did additional smoke testing on Mainnet.

**USD amount requested:** `300 USD`

### Release
To improve transparency I'll add the release efforts now separately and not combined with the Bisq Desktop Maintainer role anymore. Documentation of the release process can be found [here](https://github.com/bisq-network/bisq/blob/master/docs/release-process.md).

As the last three releases always required a hotfix shortly after based on specific OS setups we'll need to change release testing to include as many contributors as possible to at least start and smoke test a release candidate. I'll announce more details shortly after our next v1.2.9 hotfix release.

**USD amount requested:** `720 USD`

### Support
Monitoring the support channel during my [L2 times](https://calendar.google.com/calendar/embed?src=u4eea6bffk10b76l2cmb86eqqc%40group.calendar.google.com&ctz=Europe%2FVienna) and am investigation atm one issue where funds are still locked up although trades were completed successfully.
Helping out L1 support whenever needed.

Support cases:

- [Funds are still locked after trade has been completed](https://github.com/bisq-network/bisq/issues/3975)
- [App not launching on Windows](https://github.com/bisq-network/bisq/issues/3998)
- Locked funds after a successful trade

**USD amount requested:** `422 USD`

## Contributions in progress

I'm focusing right now on v1.2.9 and continue to get the PR workflow more streamlined.
Besides that I'm working on [account signing improvements](https://github.com/bisq-network/projects/issues/10).

All efforts for my role as dev team lead (roughly occupied ~60% of my time) won't be put up for compensation until it is proven to have the success we are looking for.

## Roles performed

- Bisq Desktop Maintainer: https://github.com/bisq-network/roles/issues/63#issuecomment-585819704 `1000 USD`
- Analytics Maintainer: https://github.com/bisq-network/roles/issues/40#issuecomment-599416506 `80 USD`
- Bitcoin Fullnode Operator: https://github.com/bisq-network/roles/issues/67#issuecomment-599416888 `50 USD`
- GitHub Admin:  https://github.com/bisq-network/roles/issues/16#issuecomment-599417977 `25 USD`

**USD amount requested for all these roles (see detailed amount for each role):** `1155 USD`

The following are roles where I play a secondary role, and do not (necessarily) do monthly reports:

- YouTube Admin: https://github.com/bisq-network/roles/issues/56
- Bisq Events Maintainer: https://github.com/bisq-network/roles/issues/65
- Growth Maintainer: https://github.com/bisq-network/roles/issues/42
- Transifex Admin (secondary): https://github.com/bisq-network/roles/issues/20
- Bisq Design Maintainer: https://github.com/bisq-network/roles/issues/75 (primary, but on-hold because of no active work)

**Comment by cbeams** [comment] 2020-03-16 13:07
> Monitoring the support channel during my L2 times

The nature of L2 work should be push, not pull, as in L1 agents should ping you when help is needed; it shouldn't be required for you to monitor the support channel. Of course it's fine if you wish to do this, but I just want to check: how much of the `422 USD` being requested for L2 work is because of active monitoring vs actually addressing L2 issues? I assume it's mostly the latter, but I was a bit surprised by the number being that high. Were these just difficult / time-consuming issues?

Other than this question, the request looks good to me.

**Comment by cbeams** [comment] 2020-03-17 12:00
Since we're getting close to the deadline, I'd say submit your DAO proposal in any case, with my approval on this. Would be good to have the answer to the above, but we don't need to hold this up on it.

**Comment by sqrrm** [comment] 2020-03-17 14:08
I can't speak for @ripcurlx's workload from L2 support issues but for me it's been very time consuming. It's hard to differentiate though since they're genuine bugs so some of that time will be documented as dev effort and some in the support section. I have found that L1 support handles most cases that can be handled without a dev rather well. The problem is that we still have too many bugs.

**Comment by ripcurlx** [comment] 2020-03-17 15:58
> I just want to check: how much of the `422 USD` being requested for L2 work is because of active monitoring vs actually addressing L2 issues? I assume it's mostly the latter, but I was a bit surprised by the number being that high. Were these just difficult / time-consuming issues?

This was mainly caused by the locked up funds issue, which made lots of code reading and back and forth communication between the affected user necessary.

**Comment by ripcurlx** [comment] 2020-03-17 15:59
Proposal transaction ID: `dcc894597fb9fdb589c1ba78a3f7b413084795e216540024a51aed3e3c78b054`

**Comment by MwithM** [comment] 2020-03-27 19:34
closing as accepted

**Closed** 2020-03-27 19:35 UTC
Labels: was:accepted
