### ISSUE TITLE
For Cycle 23

### ISSUE THREAD

**Issue by wallclockbuilder** [bisq-network/compensation#819] opened 2021-04-03 00:36 UTC
## Summary

- **BSQ requested**: **`283.49`**
- USD requested: 618.00
- BSQ rate: 2.18 USD per BSQ

## Contributions delivered
Cycle 23

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Replace slack with Keybase | dev | 5 | [5288](https://github.com/bisq-network/bisq/pull/5288) | PR |
|Release v1.6.0 | dev | 441 | [Report](https://bisq.ontestpad.com/project/1/folder/f104/report/?auth=2b03592a51b2611bbac8d479c399ebd8) | Testing |
| Release v1.6.1 | dev | 0 | [Report](https://bisq.ontestpad.com/project/1/folder/f110/report/?auth=9ed994165a6034c2d16b7dcc5adf596d) | Testing |
| Improve takeoffer error handing | dev | 17 | [5294](https://github.com/bisq-network/bisq/pull/5294) | Code Review |
| Fix dark mode readibility of specific texts - Part 2  | dev | 7 | [5332](https://github.com/bisq-network/bisq/pull/5332) | Code Review |
| Delete issue template file  | dev | 0 | [5353](https://github.com/bisq-network/bisq/pull/5353) | Code Review |
| Remove the apparent link for cases where the trade is not available for mediators | dev | 37 | [5354](https://github.com/bisq-network/bisq/pull/5354) | Code Review |
| Add api method createcryptopaymentacct  | dev | 28 | [5356](https://github.com/bisq-network/bisq/pull/5356) | Code Review |
| Allow default fee values in leniency check  | dev | 21 | [5365](https://github.com/bisq-network/bisq/pull/5365) | Code Review |
| Fix NPE in Portfolio View when market price n/a | dev | 31 | [5385](https://github.com/bisq-network/bisq/pull/5385) | Code Review |
| Update commands for mediator/refund agent  | dev | 22 | [5323](https://github.com/bisq-network/bisq/pull/5323) | Merged PR |
| Fix typo in function name | dev | 9 | [5291](https://github.com/bisq-network/bisq/pull/5291) | Merged PR |
| Replace slack with Keybase  | dev | 0 | [5288](https://github.com/bisq-network/bisq/pull/5288) | Merged PR |
| Transaction Details dialog should display exact amount of BTC sent. No more. No less. | dev | 0 | [5305](https://github.com/bisq-network/bisq/issues/5305) | Issue leading to Merged PR |

## Contributions in progress
| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| Update testing steps.  | dev | - | [5317](https://github.com/bisq-network/bisq/pull/5317) | - |
| Change file mentioned to from .desktop to .service  | dev | - | [5319](https://github.com/bisq-network/bisq/pull/5319) | - |
| Generate more than 1 block(regtest) | dev | - | [5355](https://github.com/bisq-network/bisq/pull/5355) | - |
| Add tooltip(on hover) to BondUnlockTime column title | dev | - | [5275](https://github.com/bisq-network/bisq/issues/5275) | - |
| Temporary solution for high mining fees | dev | - | [5282](https://github.com/bisq-network/bisq/issues/5282) | - |
| Publish ALL pending offers when mining fee is low. | dev | - | [5296](https://github.com/bisq-network/bisq/issues/5296) | - |
| Unhide custom mining fee option(from settings-page to send-bitcoin-page) | dev | - | [5298](https://github.com/bisq-network/bisq/issues/5298) | - |
| Unhide custom mining fee option for sending BSQ | dev | - | [5304](https://github.com/bisq-network/bisq/issues/5304) | - |
| Let user enter human friendly time for locking up BSQ. Let Bisq handle the conversion to block time. | dev | - | [5306](https://github.com/bisq-network/bisq/issues/5306) | - |

**Comment by ripcurlx** [comment] 2021-04-05 19:30
@wallclockbuilder Please don't create test scripts on your own for new releases, as it leads to unnecessary testing cycles. In this case you were testing for v1.6.1 account creation, but the changes in the release https://github.com/bisq-network/bisq/releases/tag/v1.6.1 didn't touch this part of the code at all. The amount for release testing of v1.6.0 also seems to be higher than what we compensated in the past for this work.

Thanks for doing code reviews as well, but here are a couple of remarks to your reviews. I think if you leave an ACK or utACK at a PR it would be good to add what you tested or reviewed in more detail. Otherwise it is quite hard to evaluate without some track record in the project if the compensation request asked for does match your review work.

- https://github.com/bisq-network/bisq/pull/5356: Why was the code review for this PR so much more effort?
- https://github.com/bisq-network/bisq/pull/5353: What did you ACK or tested? (only a file was deleted in this PR)
- https://github.com/bisq-network/bisq/pull/5354: In this case where the review amount exceeds the amount of the contribution I think the amount is out of proportion.

Looking at https://github.com/bisq-network/bisq/pull/5288 an other CRs I don't think this amount requested is just.


https://github.com/bisq-network/bisq/issues/5305: We very rarely accepted the issue creation for compensation in the past and only if there was extensive testing back and forth between developers and reporters.

**Comment by wallclockbuilder** [comment] 2021-04-05 21:07
- [5356](https://github.com/bisq-network/bisq/pull/5356): Setup time required to switch into API enduser context. Being a first time user(tester), there were some sunk costs in setup time. This setup will not need to be done again for other tests.
- [5353](https://github.com/bisq-network/bisq/pull/5353) Adjusted the number. Should have been a utACK.
- [5354](https://github.com/bisq-network/bisq/pull/5354)Testing required switching into contributor's context. To get there meant running alice, bob, and mediator instances, alice creating an offer, bob taking the offer, alice opening a mediation, before testing the interface.  Contributor already had this context setup so makes sense it took him/her less time.
- [5288](https://github.com/bisq-network/bisq/pull/5288) I've adjusted that.
- [5305](https://github.com/bisq-network/bisq/pull/5353) Adjusted.

**Comment by wallclockbuilder** [comment] 2021-04-05 22:28
- Release v1.6.1 Adjusted to 0.

**Comment by wallclockbuilder** [comment] 2021-04-05 22:51
The testing is in the ball park of the most [recent tests](https://github.com/bisq-network/compensation/issues/795) approved. Mine is a few percentage points higher only because I'm a first timer. It'll get lower as I do more rounds.

**Comment by ripcurlx** [comment] 2021-04-07 14:11
> * [5356](https://github.com/bisq-network/bisq/pull/5356): Setup time required to switch into API enduser context. Being a first time user(tester), there were some sunk costs in setup time. This setup will not need to be done again for other tests.

> 5354Testing required switching into contributor's context. To get there meant running alice, bob, and mediator instances, alice creating an offer, bob taking the offer, alice opening a mediation, before testing the interface. Contributor already had this context setup so makes sense it took him/her less time.

As we don't want to incentivize time spent, but rather what is delivered it would be great to keep out of your testing and review efforts anything that is related to one-time setup efforts. So it is easier to review for everyone who is checking CRs without the need to know if someone is already around for a long time or new to Bisq.

**Comment by wallclockbuilder** [comment] 2021-04-07 15:34
Will do!

**Comment by wallclockbuilder** [comment] 2021-04-07 15:48
5354: Adjusted from 128 to 28
5356: Adjusted from 87 to 37

**Comment by wallclockbuilder** [comment] 2021-04-08 16:02
@ripcurlx All issues addressed. Ready for review.

**Comment by MwithM** [comment] 2021-04-09 09:59
The proposal phase time has concluded, you will have to resubmit this for next cycle. It would be nice if you finally get it approved though. You can keep the review even if the issue is closed.

Closed as not submitted.

**Closed as completed by MwithM** 2021-04-09 09:59 UTC
Labels: was:not submitted, team:dev, parsed:valid

**Comment by wallclockbuilder** [comment] 2021-04-09 14:14
Alright

**Comment by ripcurlx** [comment] 2021-04-09 17:37
> Alright

Sorry about this delayed reviews. I had and have still personal issues that consumed most of my time over the last week. I'll do another proper review of the changes on Monday. Sorry that you missed because of this the chance to submit your CR for this cycle.
