### ISSUE TITLE
For Cycle 17

### ISSUE THREAD

**Issue by cbeams** [bisq-network/compensation#668] opened 2020-09-22 11:17 UTC
## Summary

- **BSQ requested**: **`74.63`** 
- USD requested: 50
- BSQ rate: [0.67](https://github.com/bisq-network/compensation/issues/656) USD per BSQ
- Previous compensation request (if applicable): #648

## Contributions delivered

| Title | Team | USD | Link | Notes |
| --- | --- | --- | --- | --- |
| DNS Admin | admin* | 25 | https://github.com/bisq-network/roles/issues/18#issuecomment-696659113 | 
| Roles Maintainer | admin* | 25 | https://github.com/bisq-network/roles/issues/28#issuecomment-696658750 |

## Other notes

See my comment about continuing to play the GitHub Admin role as a secondary at https://github.com/bisq-network/compensation/issues/668.

**Comment by cbeams** [comment] 2020-09-22 11:22
Please approve, @m52go.

**Comment by m52go** [comment] 2020-09-22 21:54
[Approved](https://bisq.wiki/Compensation#Team_Lead)—please submit to the DAO and post txid here.

**Comment by cbeams** [comment] 2020-09-24 08:09
> > Please submit to the DAO and post TXID here.
> 
> `cf1216d60bb0639a95a4604b038e15dd500cb576ceb38f508a89379bb3344cbe`

**Comment by MwithM** [comment] 2020-10-05 06:38
Closed as rejected

**Closed as completed by MwithM** 2020-10-05 06:38 UTC
Labels: was:rejected, team:admin, parsed:valid

**Comment by cbeams** [comment] 2020-10-05 06:56
Attn: @chimp1984, @sqrrm 

@MwithM [wrote](https://github.com/bisq-network/compensation/issues/668#issuecomment-703430405):

> Closed as rejected

This seems very unusual. I've never had a request rejected before; this appears to be the only request rejected during this cycle; and it got unanimous downvotes! (I was unable to add my own upvote because I missed the voting deadline)

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/301810/95048000-58164a80-06e7-11eb-93be-b2f47f37a522.png">
<img width="998" alt="image" src="https://user-images.githubusercontent.com/301810/95048004-5a78a480-06e7-11eb-9d1a-aea7e225ec6f.png">

Any ideas how this might have happened? Was it something I said? ;)

I've also noticed that my BSQ issuance for Cycle 16 (which was approved, see #648) has not come through to my BSQ wallet. May be a completely separate issue, but seems worth mentioning here.

**Comment by sqrrm** [comment] 2020-10-05 11:04
@cbeams I suspect your proposal didn't propagate before the vote. I didn't see it for example. I'm a bit fuzzy on exactly how the votes are counted, but I think that since your proposal wasn't part of the majority view of proposals it will count all votes that were part of the majority view as rejecting all non majority view proposals.

It looks like I didn't have it on Oct 1 and received it on Oct 4. That's strange since it looks like it was created 2020-09-25 06:25. Perhaps your log will show if you managed to broadcast it properly when it was created. My log for when I received it:
```
Oct-04 14:54:56.609 [JavaFX Application Thread] INFO  b.n.p.p.g.RequestDataHandler: 
#################################################################
Connected to node: fl3mmribyxgrv63c.onion:8000
Received 1748 instances
BlindVotePayload: 1
RefundAgent: 1
Filter: 1
TempProposalPayload: 2
TradeStatistics2: 300
MailboxStoragePayload: 745
ProposalPayload: 1
Mediator: 2
Alert: 1
AccountAgeWitness: 170
OfferPayload: 478
SignedWitness: 46
################################################################# 
```

**Comment by cbeams** [comment] 2020-10-05 15:54
Thanks, @sqrrm. Relevant bits from my log:

`Sep-24 09:48:14.689 [JavaFX Application Thread] INFO  b.c.d.g.p.MyProposalListService: Proposal tx has been published. TxId=cf1216d60bb0639a95a4604b038e15dd500cb576ceb38f508a89379bb3344cbe
`

`Oct-04 08:56:18.426 [JavaFX Application Thread] INFO  b.c.d.g.b.BallotListService: We create a new ballot with a proposal and add it to our list. Vote is null at that moment. proposalTxId=cf1216d60bb0639a95a4604b038e15dd500cb576ceb38f508a89379bb3344cbe`

```
Oct-05 08:42:30.757 [JavaFX Application Thread] WARN  b.c.d.g.v.VoteResultService: We have a proposal which was not part of our blind vote and
reject it. Proposal=CompensationProposal{
     requestedBsq=7463,
     bsqAddress='B13i3GQgdiZpHDdrjiL7Z16xxnupuj4gc5k'
} Proposal{
     txId='cf1216d60bb0639a95a4604b038e15dd500cb576ceb38f508a89379bb3344cbe',
     name='cbeams',
     link='https://bisq.network/dao-compensation/668',
     txId='cf1216d60bb0639a95a4604b038e15dd500cb576ceb38f508a89379bb3344cbe',
     version=1,
     creationDate=Thu Sep 24 09:46:51 CEST 2020
}
```

The last block repeats 9 times.

Still not sure what happened or went wrong, further ideas welcome. Seems like a one-off for now; I'll resubmit next cycle.

**Comment by sqrrm** [comment] 2020-10-05 15:58
The tx obviously broadcast properly since it was confirmed on the 25th, but the p2p data probably didn't get distributed until the 4th which was too late. Anything more from the 24th about the p2p data?

**Comment by cbeams** [comment] 2020-10-05 16:08
Just these lines, perhaps:

`Sep-24 09:48:14.612 [JavaFX Application Thread] INFO  b.c.d.g.p.ProposalService: We received a TempProposalPayload and store it to our protectedStoreList. proposalTxId=cf1216d60bb0639a95a4604b038e15dd500cb576ceb38f508a89379bb3344cbe`

`Sep-24 09:48:14.618 [JavaFX Application Thread] INFO  b.c.d.g.p.MyProposalListService: TempProposalPayload has been added to P2P network. ProposalTxId=cf1216d60bb0639a95a4604b038e15dd500cb576ceb38f508a89379bb3344cbe`

**Comment by chimp1984** [comment] 2020-10-06 01:39
@cbeams can you send me the full logs (all 10 files). Maybe its related to the late BSQ tx from last cycle? I assume as well that the proposal data did not got distributed in time or have been invalid for yet unknown reasons.

**Comment by chimp1984** [comment] 2020-10-06 02:32
Seems we have one more irregular tx. The others have been late proposals. Likely thats the case here as well... investigating...
<img width="280" alt="Screen Shot 2020-10-05 at 21 24 52" src="https://user-images.githubusercontent.com/54558767/95152193-1ec6f480-0752-11eb-9c2d-c7a0e0add76f.png">

**Comment by chimp1984** [comment] 2020-10-06 02:58
Added breakpoint there and got your tx. So seems that the proposal data did not arriv ein time. If you quite the app quickly after proposal creation that can happen. Have not investigated further so far... but seems likely thats the issue.
<img width="1139" alt="Screen Shot 2020-10-05 at 21 55 50" src="https://user-images.githubusercontent.com/54558767/95153697-ad894080-0755-11eb-9245-1d40116f858b.png">

**Comment by cbeams** [comment] 2020-10-06 06:18
> @cbeams can you send me the full logs (all 10 files).

Sure. They're available at keybase://private/chimp1984%2Ccbeams/compensation-668-logs.tgz

**Comment by cbeams** [comment] 2020-10-23 13:14
Heads up: I'm putting together my compensation request for Cycle 18 now, and I will include the amount requested in this compensation request there.
