### ISSUE TITLE
For cycle 11 

### ISSUE THREAD

**Issue by ArnaudFR86** [bisq-network/compensation#505] opened 2020-03-08 17:29 UTC
## Summary

- BSQ requested: **327**
 
Using 0.66 rate:  215.845 /0.66 = 327

## Contributions delivered

French translation:
1941  words translated x 0.07 = **135.87**
2285 words revised x 0.035 = **79,975**

December
![bisq2020](https://user-images.githubusercontent.com/50170753/76168034-c30c9c80-616b-11ea-9206-e7ced1be8dd7.JPG)

January
![bisq20202](https://user-images.githubusercontent.com/50170753/76168035-c43dc980-616b-11ea-8b7c-2db156da07cc.JPG)

![bisqtranslated2020](https://user-images.githubusercontent.com/50170753/76168889-cb68d580-6173-11ea-8ca8-66a3a9e6eac2.JPG)

![reviewingbisq2020](https://user-images.githubusercontent.com/50170753/76168890-cdcb2f80-6173-11ea-8087-0fe54737ba1a.JPG)

Edit2: I edited two times to provide  better screenshots from Transiflex and recalculed using the numbers provided in the two last pictures, and not the two showing the dashboard numbers ( I think this is the best way to proceed ?).

**Comment by MwithM** [comment] 2020-03-12 06:56
Please remove WIP label from title and comment here to notify me.

**Comment by ArnaudFR86** [comment] 2020-03-12 08:51
> 
> 
> Please remove WIP label from title and comment here to notify me.

@MwithM Hello, I removed WIP label from title.

**Comment by MwithM** [comment] 2020-03-13 15:45
Your last compensation request was for Cycle 5 on 16sep19. This translations are since 15dec19 and you did not ask for compensation until now. I think it's necessary for DAO that you explain why this compensation was not requested earlier.
This was not planned because I was not aware of backlog in compensated translations, but there's ennough budget for this at this cycle. I'm waiting for your explanation about why this wasn't requested earlier to approve it.

**Comment by MwithM** [comment] 2020-03-13 16:35
Lots of strings counted as translated are indeed reviewed. I'm affraid we're counting them twice, as reviewed (because you are a reviewer) and as translated, because you're the last to update it.
That's a known issue and I'm not sure how to properly count or estimate this. Maybe you remember what was translated or reviewed better.
@trigger67 is the other translator/reviewer that worked with FR strings and his last request was for cycle 8 at 12dec19. I wonder if he still has to send a compensation.

![ArnaudFR 1](https://user-images.githubusercontent.com/50149324/76640541-6d136c80-6550-11ea-9d10-f6f4f1966f69.JPG)

![ArnaudFR 2](https://user-images.githubusercontent.com/50149324/76640661-99c78400-6550-11ea-9fbc-00f546e504f0.JPG)

![ArnaudFR3](https://user-images.githubusercontent.com/50149324/76640670-9fbd6500-6550-11ea-83b8-608ac628b2bb.JPG)

![ArnaudFR4](https://user-images.githubusercontent.com/50149324/76640872-f7f46700-6550-11ea-986f-dfe88c1a284c.JPG)

**Comment by ArnaudFR86** [comment] 2020-03-14 04:12
I worked with @trigger67 until January the 14th to finish the reviewing part, then as he tolds me it was late  to get his compensation validated on time I wanted to wait more to be sure that mine was not going to be rejected and that the work was delivered to customer. 

When I wanted to proceed to my compensation request, I' saw the post of @m52go saying: 
"channel
please notice: guidelines for submitting compensation requests have changed.
see this post for details:
https://github.com/orgs/bisq-network/teams/dao/discussions/2""
As I can not access/read the document I waited more thinking some changes were maybe going on.

The issue with the reviewing of some strings is that @trigger67 wanted to respect the French punctuation standard that consist to add a space after the ":" and as I checked others translators works (in others langage), there is none, so I proceed to changes, that penalized trigger for his compensation reducing his total, and we talked together about that to find a solution but ended letting it as it is.

**Comment by ArnaudFR86** [comment] 2020-03-14 04:50
Iam not sure I can remember which was translated or reviewed better, but as I can provide the reason why I changed the strings you pasted up.

The first one, I changed the verb "to reject" for "to refuse" as to me it seems more relevant.
The second because the accent is missing.
The third is about the space issue explained earlier.

**Comment by MwithM** [comment] 2020-03-14 12:29
There's justification for all your little changes performed on this strings, because that's what a reviewer must do. The problem is that Transifex counts as translated all reviews that needed a change, no matter how little. That implies that on this request, for some strings, you're going to be compensated as translator and reviewer but it should be only as reviewer.

![paste](https://user-images.githubusercontent.com/50149324/76681770-e4034080-65f6-11ea-8fa1-1bed307d887b.png)

This are the kind of strings I'm worried about. There's changes on this string, #893, since more than 10 months ago. Every time this string has changed, a compensation request could have been done for it.
I know you're not the only one who has this issue, and that sometimes translations are lost when source files are updated. I want to create awareness about it.

**Comment by ArnaudFR86** [comment] 2020-03-14 16:03
About the last French translation and reviewing, as I was alone to do the work, I translated, and reviewed my own work, and for that reason none reviewing have been charged. 

https://github.com/bisq-network/compensation/issues/341

Since then, I noticed that @trigger67 joined the French translator team and contacted him on Twitter and we started to work together and talk on Keybase on 2th December sharing the remainging work.  We talked also about the strings problem (that could be unfairly compensated for him), and it ended up him saying that in the worst case scenario he could loose couple BSQ, not making it a big deal. I contacted Trigger yesterday on Keybase informing him that he was cited it this compensation request and that he can comment about it.

**Comment by MwithM** [comment] 2020-03-15 14:06
Ok, submit your request to DAO and publish TXID. Thanks.

**Comment by ArnaudFR86** [comment] 2020-03-15 16:29
I submitted the compensation request in DAO, the TXID is: 

23564d0a3b85b7ec373c7861b5b8aa2185f2ba3771a57300159420e44c6911ce

https://bsq.sqrrm.net/tx.html?tx=23564d0a3b85b7ec373c7861b5b8aa2185f2ba3771a57300159420e44c6911ce

Thanks.

**Comment by MwithM** [comment] 2020-03-27 19:37
closing as accepted

**Closed by MwithM** 2020-03-27 19:37 UTC
Labels: was:accepted
