### ISSUE TITLE
For March 2019

### ISSUE THREAD

**Issue by Wimking1987** [bisq-network/compensation#254] opened 2019-03-30 18:18 UTC
BSQ requested:350
BSQ address: B14Cictu1JaHoR3wCF4uq9D3LxcxZvk4FYs

![bisq_network_visualisation](https://user-images.githubusercontent.com/48585299/55280035-6defc600-5320-11e9-9138-667f3b6043c2.jpg)

https://github.com/Wimking1987/bisq-design/commit/5773112cba134015db5bfb685ee8799261581f1f

The design will be used in the blog and can be used everywhere when we need a visualisation of the network:

https://bisq.network/blog/an-overview-of-the-bisq-network/

**Comment by pedromvpg** [comment] 2019-03-31 17:39
Hey @Wimking1987,

It looks good but I don't think this is the best way to use the "cat" mark. For these visualization diagrams can we focus more on how different parts of the network integrate with each other?
- the Bitcoin blockchain
- the Bisq netwerk
- the Bisq DAO

I would also avoid any gradients, shadows, and dimensionality as it don't really match the rest of the aesthetics. Flatter uses of the background are more in tune with the rest of the materials.

Have you checked the ones on the dao page?
https://bisq.network/dao/

**Comment by ManfredKarrer** [comment] 2019-03-31 18:00
@Wimking1987 
For background, @pedromvpg is the designer who did all our rebranding and redesign.

**Comment by Wimking1987** [comment] 2019-03-31 18:13
Thanks a lot for the feedback. Will try to be closer to your visualisations @pedromvpg and will have a look how the different parts integrate with each other.

**Comment by ManfredKarrer** [comment] 2019-03-31 18:16
@Wimking1987 I am not sure if we want to use that design on the webpage as it is as we want to stick with the design line of @pedromvpg . In case your request gets rejected it does not mean it was bad quality but if we will not use it in Bisq it is not really justified that the Bisq DAO issue a compensation. I am aware that this might create a bit of frustration and was likely caused by lack of communication with those who are more familiar with our design strategies. Hope you understand that and continue to contribute! Best would be to stay in close loop with @pedromvpg . You find him on Slack as well as pedrogoncalves.

**Comment by arunasurya** [comment] 2019-04-01 15:06
Hi everyone,

I just noticed this thread and would like to voice my opinion here. It is I who invited @Wimking1987 to help me with design for the Bisq academy, which, if I understood correctly, @ManfredKarrer believed had value for the broader Bisq community. I also thought that we could add images for our weekly blog posts to enhance their attractiveness. Both of these sites do not require us to stick to the specific format of the current design by @pedromvpg. As a creator of the Bisq academy, I would like to have the freedom to work with other creative people to implement my vision. I have already added Wim's image both to my Bisq network blog post and Academy page, so I truly believe that Wim has created value for the community. I hope that this makes sense.

**Comment by arunasurya** [comment] 2019-04-04 12:03
I now understand the situation better, and the need for the consistent design not only on the website but other sites associated with Bisq such as Medium's Bisq publication. For future design related things, I will run things by @pedromvpg.

**Comment by arunasurya** [comment] 2019-04-04 18:31
Upon thinking about this further, I find it constraining not to be able to use designs by other designers for projects that are not published directly on the Bisq site. I understand the need for consistency on the Bisq website but I believe that we can be more flexible on other sites, as long as we don't change the core logo (the cat) itself. I would like to use Wim's design on my github site as well as in my blog post on Medium because it is pretty and provides a nice visual of the network. I suggested using the cat logo to represent the nodes, in the same way the Bitcoin network is represented on other sites. I have removed the logo for now but would like to add it back.

**Comment by m52go** [comment] 2019-04-04 18:35
@arunasurya I think the intention is to make the design approach consistent, not that all design is done by the same designer. I agree that the Bisq aesthetic should be consistent across channels as much as possible (i.e., wherever it can be managed).

**Comment by ripcurlx** [comment] 2019-04-06 07:52
Closing as complete, see https://github.com/bisq-network/compensation/issues/243#issuecomment-480483512.

**Closed by ripcurlx** 2019-04-06 07:52 UTC
