### ISSUE TITLE
For Cycle 8

### ISSUE THREAD

**Issue by wdljt6** [bisq-network/compensation#421] opened 2019-11-29 13:36 UTC
## Summary

 - BSQ requested: 2096.59

### Bisq desktop in Simplified Chinese
928 words translated

### Bisq website in Simplified Chinese
140 words translated
3439 words edited (in July, didn't compensated before)

### Bisq desktop in Traditional Chinese
16603 words translated

### Bisq website in Traditional Chinese
4870 words translated

### Translation work summary (2096.59 BSQ)
Simplified Chinese and Traditional Chinese are [core languages](https://github.com/arunasurya/bisqtransifex/blob/master/translatordocumentation.md#core-languages).
Its translation work uses the [compensation rate](https://github.com/arunasurya/bisqtransifex/blob/master/translatordocumentation.md#compensation-requests) as followed:

Translated: (928 + 140 + 16603 + 4870) x 0.07 = 1577.87 USD
Edited: 3439 x 0.035 = 120.365 USD

BSQ amount: (1577.87 + 120.365) / 0.81 = 2096.59 BSQ

![IMG_20191215_130927](https://user-images.githubusercontent.com/45174116/70858387-4dae7880-1f3c-11ea-938b-4ad217627bc8.jpg)
![IMG_20191215_130951](https://user-images.githubusercontent.com/45174116/70858389-5141ff80-1f3c-11ea-96cb-83b766b7ad28.jpg)

Zh-hant translation for bisq-website and bisq-desktop was mostly done in September, which is delivered to website and desktop application lately, since is requested to compensate now.

[Work progress last time](https://github.com/bisq-network/compensation/issues/391)

**Comment by ripcurlx** [comment] 2019-12-16 11:35
> ### Bisq desktop in Traditional Chinese
> 16603 words translated

Words to be translated are in total `18,953`

![Bildschirmfoto 2019-12-16 um 12 29 54](https://user-images.githubusercontent.com/170962/70903750-d5a98680-1fff-11ea-973d-1c764359fd25.png)

Adding up your compensation request and the one from https://github.com/bisq-network/compensation/issues/420 means for traditional Chinese:

- 23,199 words translated
- 23,445 words reviewed

@wdljt6 @ff98sha Is this caused by continuous changes and re-reviews of the same words?

**Comment by ff98sha** [comment] 2019-12-16 11:48
@ripcurlx The continous change of source strings is sure to cause this problem. Some of the stats may contain partial duplicate parts in the updated string, and others may caused by the abandoned strings in the latest release. I think it's a common problem in calculating the words. So how did you solve this kind of problem last time?

**Comment by wdljt6** [comment] 2019-12-16 12:10
@ripcurlx The first traditional Chinese translation was completed in September, and the translation status was reset later because some entries were changed. The translation was completed again in December, so the sum may be greater than the total number of words

**Comment by ripcurlx** [comment] 2019-12-16 12:41
@ff98sha @wdljt6 I thought so -  just wanted to clear things up as it might not be so obvious for every stakeholder.

**Comment by wdljt6** [comment] 2019-12-16 12:46
@ripcurlx I can upload all the data screenshots on transifex if necessary

**Comment by arunasurya** [comment] 2019-12-17 20:17
@ff98sha , @wdljt6 , are you planning to resubmit your compensation requests with the corrected total number of words? Also, can you provide screenshots for your work as described in the translation documentation [here](https://github.com/arunasurya/bisqtransifex/blob/master/translationguidelines.md)? Thanks!

**Comment by ff98sha** [comment] 2019-12-17 22:30
@arunasurya So only 18,953 words should be for compensation?

**Comment by wdljt6** [comment] 2019-12-17 23:14
@arunasurya If you add up all the translations in simplified Chinese, that's more than 18,953 words. So part of the reason why these are over 18,953 words is because of the translation reset and re-translation, not because we added them maliciously.

**Comment by arunasurya** [comment] 2019-12-17 23:49
@wdljt6 , I did not mean to imply any bad intent, I am just trying to understand better the word count. I have not been involved in any coordination of Chinese translations, so I am learning along with the process.

**Comment by ff98sha** [comment] 2019-12-18 06:33
@arunasurya IMO the current word count is the actual work paid. The screenshot described in the document isn't accurated as it may contain edited words not included in reviewer's compensation, and the description should be updated.

**Comment by MwithM** [comment] 2019-12-22 13:44
Closed as accepted

**Closed by MwithM** 2019-12-22 13:44 UTC
