### ISSUE TITLE
BSQ rate for Cycle 22 is 1.21 USD per 1 BSQ

### ISSUE THREAD

**Issue by MwithM** [bisq-network/compensation#782] opened 2021-02-10 16:44 UTC
The recommended rate to be used for compensation requests on cycle 22 is 1.21 USD/BSQ.

30 Day BTC/BSQ: 0.00006020
30 Day USD/BSQ: 2.1
90 Day BTC/BSQ: 0.00004960
90 Day USD/BSQ: 1.21

More info about the Compensation process at https://bisq.wiki/Compensation
Rate for last cycle: #755
Proposal for this cycle: https://github.com/bisq-network/proposals/issues/300

There will be some contributors who did not ask for reimbursement requests because Bisq could have exceeded the max amount issued per cycle on Cycle 21 that will probably use different compensation rates. It's ok as long as the DAO agrees with it.

**Comment by chimp1984** [comment] 2021-02-10 18:42
> on cycle 21 is 

Should be on cycle 22, no?

I think we should use the 30 day average instead the 90 days for the next price proposal. We have about 2 weeks delay between the proposal and the nex cycle and then 4 weeks for the cycle, so the payout rate is already 6 weeks in the past and then with the 90 days average so get a price too much in the past. 

Current BSQ price  is about 2.6 USD (30 day average). So with the 0.75 USD rate we use in cycle 21 contributors get 3.5 times more if they manage to sell to current rate (I know liquidity is still not great but with a bit of patiece one can sell).  January had about 165k USD BSQ volume and I think the BM has not been active in that period.

With a 30 day average we still set the price 6 weeks before the BSQ gets issued, so about a price which is already 2 months old. Maybe we can do the proposal later (1 week before new cycle) or even during the new cycle and contributor have to waint until price is defined before making their requests?

<img width="952" alt="Screen Shot 2021-02-10 at 13 31 29" src="https://user-images.githubusercontent.com/54558767/107555188-dd819e00-6ba4-11eb-8dc2-ac6cf1ad31aa.png">

**Comment by MwithM** [comment] 2021-02-10 19:42
I don't agree with that. Other than a sudden BSQ price rise, nothing has changed. The reasons to use this compensation rate model is the same as when it started.
The reason to use a large mean for contributions was to make contributors commit with the project on the long term. That helps to stabilize BSQ price too.
As long as we accept that there will be times where our contributions will be worth less at the time they're paid because the spot market price is lower than the 90 day average, that's ok. And that, the harsh part, was properly managed by contributors (see cycle [10](https://github.com/bisq-network/compensation/issues/475), [9](https://github.com/bisq-network/compensation/issues/449) and [8](https://github.com/bisq-network/compensation/issues/414#issuecomment-555596868)). 
BSQ price has been, in my opinion, suprisignly stable until now though. I think that contributors need to understand that if this way to calculate the rate for contributions is kept, it will have be kept also if there is a sudden decrease in BSQ price.

Since the outliers [issue](https://github.com/bisq-network/proposals/issues/270) and the PR to address it, there's been no controversy on the price to use. I think that this announcement is doesn't have to be done at the review request submission deadline anymore and we could go back to the older way, which was announcing it at the beginning of the cycle.

**Comment by flix1** [comment] 2021-02-10 20:16
Whatever price criteria is used (30 or 90 day avg) I think the most important meta-issue is that it is predictable. 

There will ALWAYS be somebody who benefits or stands to lose with a change of rules in BSQ valuation, therefore to avoid disagreements, hurt feelings, or some collaborators feeling cheated... it is very important that the rule is known BEFORE they start to work on the cycle that will be paid for under that rule.

That being said, I doubt the price is going to stick around here, it was pretty distorted by that failed cycle. So the evening out of a longer avg will probably not look so bad in a month or 2.

![image](https://user-images.githubusercontent.com/4233784/107568426-3eca6100-6be7-11eb-9330-b99e19ab5cd2.png)

**Comment by chimp1984** [comment] 2021-02-10 22:35
Sure volatility cannot be avoided and there will always be a winner and a loser when volatility is involved, but the risk increases with longer time periods. We use a short term adjustment period for the BSQ rate (users would not accept a long term historical price anyway) and a long term rate for the issuance. 

So the balance of what we issue and what we burn gets out of balance. 

It will also create a secondary "mental" price where voters will consider the real current market price and might reject contributions as they feel its too expensive. This is a risk for the DAO as request would get rejected due a different price model the 2 parties have in mind.

Example: 
I worked for about 1 week on the new charts (see sreenshots below). Lets assume I will 4000 USD for that, with current rate that is 3300 BSQ. If I sell the 3300 BSQ with current market price of 2.6 USD/BSQ I will get 8580 USD. So beside to getting heavily overpaid I have the incentive to sell quickly to "cash out" the premium (that might be actual a good counter pressure to bring the price down again). A voter might consider the added value of the charts worth about 4000 USD but not 8500 USD and might reject my request. If that becomes more a trend in voting contributors will reduce their requested USD value to reduce the risk for rejection and by that balancing it again, but it will invalidates the USD as stable price metric and it gets more complicated how to findt to the "real price". E.g. I might consider the current market rate and request only 2500 USD but how to explain that to new contributors that they should reduce their USD rate by some "whatever" factor to get to a more acceptable BSQ price... I think we will see that teh "commitee price" is not the accepted price by the market (conttributos  and voters). I guess similar happens in countries where governments try to "tune" the official price and people use a secondary price when doing real business.

Another way to see it is to calculate the required trade volume to burn BSQ for the requested compensation [1].

I just checked with the live app the fee rate: 
Maker fee for a 2 BTC offer: 15 BSQ (48 USD)
Taker fee: 105 BSQ (333 USD)
So a 2 BTC trade generates 120 BSQ (381 USD) or 60 BSQ/1 BTC (with 44560 USD/BTC price and 2.6 BSQ/USD 30 day average). 
BSQ fee rate is 0.4275% of trade volume

So if I request 3300 BSQ it will require 55 BTC of trade volume to generate the BSQ fees funding my compensation request. With current volumes in the past weeks (about 100 BTC/week) that is roughly half a week of total trade volume. Or in other words we can fund about 24000 BSQ per month to be neutral with issuance.

<img width="1321" alt="Screen Shot 2021-02-10 at 17 28 45" src="https://user-images.githubusercontent.com/54558767/107581014-79230680-6bc5-11eb-81e4-5de95e283429.png">

We have issued 276k BSQ in 5 months for compensation requests (55200 BSQ per month), so that would require 920 BTC trade volume per month. Real trade volume is about 400 BTC per month (2012 BTC in 5 months). So we issue 2.3 times more than we earn.

<img width="1311" alt="Screen Shot 2021-02-10 at 17 05 13" src="https://user-images.githubusercontent.com/54558767/107578883-52170580-6bc2-11eb-81f9-45350f57b812.png">

In USD terms:
43M USD in 5 months (Sept-Jan) with a 0.4275% rate is 183825 USD or 36765 USD/month. I dont have the USD numbers of the past cycles but seems its in the same range as above in BSQ.  

<img width="1337" alt="Screen Shot 2021-02-10 at 17 03 27" src="https://user-images.githubusercontent.com/54558767/107578600-f2205f00-6bc1-11eb-82ce-5257320ef0d6.png">

An even bigger risk with a wrong aligned price is the large amounts of reimbursement costs (200K in last 2 months). Also those got overpaid heavily and depending on the details how the burningman deals with it it might cause quite another loss to the DAO. But thats a topic for another discussion...

I think that plays into the same area like https://github.com/bisq-network/bisq/discussions/5171 and also how to deal with reimbursements. Don't want to derail that issue too much by getting deeper in to the economics (and lack of data) of the DAO but I think we have to take care to be on the right track and fix issues as soon we discover them.

[1] In my model I ignore low volume trades which have a higher fee rate and BTC fees as well the fact that 50% of BTC fees go to the victims. Also further the conversion costs of the BTC to BSQ (burningman) and the other big factor of reimbursement requests and burned BSQ from delayed payout transactions.

**Comment by RefundAgent** [comment] 2021-02-11 00:38
There should not be any averaging at all and the volatility cost should be included in the compensation request made by the contributors. The past averaged price says less about the future price than the present price. It says very little about the volatility either which can be estimated using different (but simple) methods.
The present system will be warmly welcomed when the price increases and the contributors get a windfall. When the price decreases they will leave Bisq instead. Or compensate with wildly expensive compensation requests.

**Comment by wiz** [comment] 2021-02-11 03:53
There were often times in the past when the Bitcoin price crashed suddenly and because our compensation system uses a 90 day average, Bisq contributors had to accept getting paid at a rate higher than the actual market, which resulted in them getting paid less. Now because of the recent Bitcoin price increase, the market has moved in their favor, let them get the good pay for a while so it balances out from before IMO.

**Comment by chimp1984** [comment] 2021-02-11 04:11
The price rise is going on since about 4 months. So we are constantly overpaying since. With my new charts (still pending PR) you can see much better details of historical price development. There have been a bad period around Jan 2020 where price went down to about 0.45 USD. But beside that it was pretty stable.

<img width="1322" alt="Screen Shot 2021-02-10 at 22 58 05" src="https://user-images.githubusercontent.com/54558767/107601018-763f0a80-6bf3-11eb-92a3-0bcbfad719ea.png">

Please don't misunderstand me, I am a main contributor and benefit from that current model if we overpay. But I think we made a mistake to treat the 2 sides of the DAO economy differently from the rate fixing. The BSQ fee rate gets fixed as quickly as possible. Maybe we even make it automatic some day so it adjusts to short term average market rate. With compensations we have at least a one months delay which cannot easily be avoided but due that policy we use we extended that with an additional 3 months average and 2 weeks delay for the price discussion before the cycle starts. So we add more problems to the mix. 

If we don't fix that we risk that voters will change their behaviour. 
Look at some requests like my own one with 23350 USD (was for 2 months work) which got converted to 31133 BSQ. With current market rate thats about 77832 USD. Any rational investor who has a stake in Bisq would need to downvote my request or sell his BSQ as a project spending that carelessly is a bad investment.   

Also think what happens when this turns around.
So lets say we have an average rate of 2 USD and market rate goes down to 0.5 USD. A dev requests 10k USD and gets only 5k BSQ which has a market value of 2500 USD. I think we would lose quickly some contributors. Specially those who have fix costs in USD like operators. If you get instead of expected 1000 USD to pay for the servers only 250 USD you will ask the DAO to fix that as soon as possible or you cannot afford to offer your service anymore.

**Comment by spx4000** [comment] 2021-02-11 14:14
Lots of good points on this thread, but if the DAO wants to change from 90 day average, at least pick a time where the 30 day and the 90 day are equal to each other.

Some seem to forget that it was approximately 1 year of the 90 day BSQ average falling, and contributors were not able to sell at the rate that they requested.  The price slowly fell from 10,000 sats to 9,000 to 8000, 7000, 6000, 5000, 4000, 3000, 2000 and then bounced back.  Again it slowly fell all the way back to 3000 as recently as December.  Every contributor bore this hidden cost and I don't see how now that the coin flipped in their favor and the BSQ market is stronger, one could suggest to change the compensation calculation for the **express purpose** of lowering everyone's pay.

I also doubt that the BSQ market is quite as strong as is claimed in this thread, as there was an entire missing cycle of BSQ that couldn't be sold about one month ago.  I anticipate the BSQ price to fall quite a bit once everyone actually gets paid and needs to sell BSQ this week.

Just wait 90 days and the current market price will be reflected!

Seems this tendency towards micromanagement is recurring in the bisq project, as there was quite a discussion over the proper adjustment timing for the BSQ fees when someone wasn't happy with the discount % level.

This desire to tweak the outcomes of a market based function is natural but it should be resisted.  Maybe a market doesn't work as intended and something does need to be changed sometimes.  But this particular "fix" just seems to be an overreaction to a fairly unique situation where the DAO failed for a full cycle and collateral damage for cycle 22, and there was no BSQ hitting the market during a time of increased demand.

**Comment by chimp1984** [comment] 2021-02-11 23:25
> outcomes of a market based function

All those rules have been defined not by any market but as educated guesses and as it seems without enough thought. 

The DAO economy requires a system-thinking approach. It was defined with certain assumptions and not being flexible to fix mistakes (to use 2 very different time scales for setting rate for issuance and BSQ trade fees) will lead to bigger problems. 

In that case I expect that it will develop a secondary "price" as mentioned above and we might see compensation requests getting rejected because DAO voters might consider it too expensive considering actual market prices, leading to further complications and confusion. But if "let the market decide" is the credo, then let it play out that way.

**Comment by sqrrm** [comment] 2021-02-12 09:58
If we had a very liquid BSQ market I think using spot price at some point towards the end of the compensation phase would be the only reasonable conclusion.

Historically we started with a fixed rate when the DAO was new to have a bit of predictability and after a while we felt comfortable enough to move to the 90 day average. The BSQ price has been moving a lot and is now far off the spot price and the market is healthier than it was in the initial months after the launch of the DAO. Moving to using the 30 day average seems like a good step, and I think it would make the DAO more robust.

**Comment by chimp1984** [comment] 2021-02-12 13:49
> Moving to using the 30 day average seems like a good step, and I think it would make the DAO more robust.

Yes I did not mention any concrete new suggestion, but I had similar in mind. We need some average and we need to keep the manual price fixing as BSQ price could be easily manipulated. 
I think the most we can do would be to set the price as late as possible (e.g. start price fixing discussion 1 week after cycle start for 1 week, then set the rate, so comp. requests cannot be made in the first 2 weeks) and use a min 15 days average. 30 days should be fine as well and we have that already.
To do the price fixing 1 week before cycle start and make it possible to make requests at cycle start is ok as well IMO.

**Comment by MwithM** [comment] 2021-02-16 19:36
As the main objection to reduce the average mean to calculate the rate is that it's a bad time _("one could suggest to change the compensation calculation for the express purpose of lowering everyone's pay.", "Now because of the recent Bitcoin price increase, the market has moved in their favor, let them get the good pay for a while so it balances out from before IMO.")_ and that predictability is necessary _("it is very important that the rule is known BEFORE they start to work on the cycle that will be paid for under that rule.")_ I think that we could agree to **start using the 30 day average for compensations on Cycle 24**.
When the 90 day average was started to use it was stated that it was an arbitrary measure and that it could change, but I think that changes like this (trading fees, compensation and reimbursement rates...) needs to be done at a calm and steady pace. 
I'll make a proper and concrete proposal for this later to see if it's necessary to take it to a DAO voting.

**Comment by chimp1984** [comment] 2021-02-16 20:13
>  I think that we could agree to start using the 30 day average for compensations on Cycle 24.
When the 90 day average was started to use it was stated that it was an arbitrary measure and that it could change, but I think that changes like this (trading fees, compensation and reimbursement rates...) needs to be done at a calm and steady pace.

Yes agree. I did not mean to do the change for that cycle, just used that thread for discussing it.

**Comment by pazza83** [comment] 2021-02-19 02:31
> There will be some contributors who did not ask for reimbursement requests because Bisq could have exceeded the max amount issued per cycle on Cycle 21 that will probably use different compensation rates. It's ok as long as the DAO agrees with it.

I agree with contributors that did not ask for reimbursements requests on Cycle 21, or asked to be voted down for them, to submit the work delivered for Cycle 21 at the BSQ rate of Cycle 21.

**Comment by pazza83** [comment] 2021-02-19 15:19
> I think that we could agree to **start using the 30 day average for compensations on Cycle 24**.
> When the 90 day average was started to use it was stated that it was an arbitrary measure and that it could change, but I think that changes like this (trading fees, compensation and reimbursement rates...) needs to be done at a calm and steady pace.
> I'll make a proper and concrete proposal for this later to see if it's necessary to take it to a DAO voting

@MwithM Would that mean that 90 day average no longer becomes used for anything?

Following on from the discussion we had on [cycle 21 proposal](https://github.com/bisq-network/proposals/issues/301) and the discussion on this one. I would be in favor of moving to a 30 day average for all DAO requests.

I agree with @RefundAgent that there should not be any averaging all. But think 30 day averages would be an intermediate step to get closer to that goal.

**Comment by MwithM** [comment] 2021-02-20 12:09
Yes, 90 day average would not be used anymore.

**Closed as completed** 2021-03-15 09:41 UTC
Labels: parsed:invalid
